name: binjai pipeline

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-to-npmjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: npm t
      - run: npm version patch -m "v%s set by pipeline"
      - run: cp LICENSE package.json README.md dist
      - run: cd dist && npm publish
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
